#nacos配置
# 系统配置
server:
  port: ${sys.port}
# spring配置
spring:
  application:
    name: custom-project
  profiles:
    include: dubbo,druid,hikaricp,mybatis
nacos:
  discovery:
    server-addr: ${nacos.server.addr}
logging:
  config: ${sys.log.path}